apiVersion: v1
kind: ReplicationController
metadata:
  name: my-app-rc
  labels:
    type: fe
spec:
  template:
    metadata:
      name: my-app
      labels:
        app: my-app
    spec:
      containers:
      - name: nginx-container
        image: nginx
  replicas: 3
