apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  labels:
    app: myapp-service-label
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30004
  selector:
    env: production
